#!/usr/bin/env bash
if [ ! -f /var/db/vmwebadm/db.clj ]; then
	mkdir -p /var/db/vmwebadm/images
	cp !DEPLOY_PATH!/data/db.clj.example /var/db/vmwebadm/db.clj
fi
NODE_PATH="!DEPLOY_PATH!/jslib:/usr/vm/node_modules/:$NODE_PATH" node !DEPLOY_PATH!/js/client.js $*
